---
- name: install package dependencies
  sudo: true
  apt: name={{ item }} install_recommends=no
  with_items:
      - python-pip
      - python-dev    
      - python-apt
      - htop

- name: install buildslave
  sudo: true
  pip: name=buildbot-slave
