---
- name: create buildslave project directory
  file: 
    path: "{{ basedir }}"
    state: directory

- name: create buildslave
  shell: buildslave create-slave {{ basedir }} {{ buildmaster_url }} {{ buildslave_name }} "{{ buildslave_service_password | default('password') }}"
