---
- name: create buildslave project directory
  file: 
    path: "{{ basedir }}"
    state: directory

  # TODO instead of creating the config, just upload the config
- name: create buildslave default config
  shell: buildslave create-slave {{ basedir }} {{ buildmaster_url }} {{ buildslave_name }} {{ buildslave_service_password | default('password') }}
