---
- name: create default group for buildslave account
  sudo: true 
  group: name=buildslave  

- name: create dedicated buildslave account
  sudo: true
  user: 
      name: buildslave 
      # http://docs.ansible.com/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
      password: "{{ buildslave_user_salted_password | default('password') }}"
      group: buildslave
      shell: /bin/bash
